apiVersion: v1
kind: Namespace
metadata:
  name: containerized-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jgroups-kubeping-service-account
  namespace: containerized-apps
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-kubeping-pod-reader
  namespace: containerized-apps
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jgroups-kubeping-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jgroups-kubeping-pod-reader
subjects:
- kind: ServiceAccount
  name: jgroups-kubeping-service-account
  namespace: containerized-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss-cluster-hi-availability-demo
  namespace: containerized-apps
  labels: 
    app: jboss-cluster-hi-availability-demo
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: jboss-cluster-hi-availability-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jboss-cluster-hi-availability-demo
      annotations:
        v: v0.9
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      containers:
      - name: jboss-cluster-hi-availability-demo
        image: docker.io/adazes/jboss-cluster-hi-availability-demo:0.9
        imagePullPolicy: IfNotPresent
        command: ["/opt/jboss/wildfly/bin/standalone.sh"]
        args: ["-Djboss.bind.address.management=$(POD_IP)", "-Djboss.bind.address=$(POD_IP)", "-Djboss.bind.address.private=$(POD_IP)", "-Djboss.bind.address.unsecure=$(POD_IP)", "-c", "standalone-full-ha.xml", "-Djboss.messaging.cluster.password=demoMQpasswd"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_IPS
          valueFrom:
            fieldRef:
              fieldPath: status.podIPs
        - name: KUBERNETES_LABELS 
          value: app=jboss-cluster-hi-availability-demo
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports: 
          - name: http
            containerPort: 8080
          - containerPort: 9990
          - containerPort: 7600
          - containerPort: 8888
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "1512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9990
          initialDelaySeconds: 60
          periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jboss-cluster-hi-availability-service-demo
  namespace: containerized-apps
  labels:
    app: jboss-cluster-hi-availability-demo
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 32000
  selector:
    app: jboss-cluster-hi-availability-demo
