apiVersion: v1
kind: Namespace
metadata:
  name: containerized-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss-cluster-hi-availability-demo
  namespace: containerized-apps
  labels: 
    app: jboss-cluster-hi-availability-demo
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: jboss-cluster-hi-availability-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jboss-cluster-hi-availability-demo
      annotations:
        v: v0.1
    spec:
      containers:
      - name: jboss-cluster-hi-availability-demo
        image: docker.io/adazes/jboss-cluster-hi-availability-demo:0.8
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "ip=$(awk 'END{print $1}' /etc/hosts) && /opt/jboss/wildfly/bin/standalone.sh -Djboss.bind.address.management=$ip -Djboss.bind.address=$ip -Djboss.bind.address.private=$ip -Djboss.bind.address.unsecure=$ip -c standalone-full-ha.xml -u 230.0.0.4"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_IPS
          valueFrom:
            fieldRef:
              fieldPath: status.podIPs
        ports: 
          - name: http
            containerPort: 8080
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9990
          initialDelaySeconds: 60
          periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jboss-cluster-hi-availability-service-demo
  namespace: containerized-apps
  labels:
    app: jboss-cluster-hi-availability-demo
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 32000
  selector:
    app: jboss-cluster-hi-availability-demo
