FROM quay.io/wildfly/wildfly
# RUN /opt/jboss/wildfly/bin/add-user.sh -m -u admin -p safer-to-set-from-container-instead --silent

# example of containerized app:
ADD target/jboss-cluster-ha-demo.war /opt/jboss/wildfly/standalone/deployments/